### ISSUE TITLE
How to share global flow dependencies

### ISSUE THREAD

**Issue by EvHaus** [ImmoweltGroup/flow-mono-cli#105]
I'm using a `lerna` project with the following structure:

```
my_project/
    .flowconfig
    shared_types/
        some_shared_types.js
    packages/
        sub_package_a/
        sub_package_b/
```

Where the file `shared_types/some_shared_types.js` contains global flow type definitions that I want to re-use for all the sub packages.

I've included it in the `.flowconfig` as:

```
[libs]
shared_types
```

And it works great if I run `flow check` from the root of my project. However, if I go into a specific package (eg. `sub_package_a`) and try to run flow there, those shared types aren't found anymore.

This makes sense, since `flow-mono create-symlinks` simply symlinks the `.flowconfig` into the `sub_package_a` directory, causing the `libs` directory to point to invalid location. What I need is to have it point to `../../shared_types` instead.

Is this a problem that `flow-mono-cli` can solve for me somehow? Am I approaching global shared content incorrectly?

Is the solution for each package to have its own custom `.flowconfig`?

**Comment by Inkdpixels** [comment]
Hey @EvHaus, glad you found this package. Sadly for this specific problem there is no built in solution in flow-mono-cli as of now. We faced the same problems however and solved it by moving all "global" or "shared types" into the root "flow_typed" folder which all flow instances read by using the `[libs]` option of flow itself.

Using the `flow-mono create-symlinks` command you can also maintain a single flow config for all packages, so it is less of a hassle/no repitition when adding the following option to your `.flowconfig` file.

```
#
# Include patched typings from the root of the mono-repo.
#
./../../flow-typed/
```

**Comment by EvHaus** [comment]
Thanks for the response.
