### ISSUE TITLE
Not working for node 6

### ISSUE THREAD

**Issue by k15a** [ImmoweltGroup/flow-mono-cli#18]
As described [here](https://github.com/flowtype/flow-typed/issues/1391#issuecomment-353290964) flow-mono-cli is not working with node 6. If flow-mono-cli is also working on node 6 it would be great if you could change the engine field in the package.json so yarn users can install this tool. Currently it is
```js
  "engines": {
    "node": ">=8.8.0"
  },
```
Yarn strictly checks the node version and doesn't allow to install it on a lower node version.

**Comment by Inkdpixels** [comment]
Hey @k15a - While it is possible to transpile some features of Node 8 back to older versions, we urge everybody to upgrade to Node 8 as soon as possible since this is a task everybody has to do anyway at some point.
