### ISSUE TITLE
Ability to use with plain lerna

### ISSUE THREAD

**Issue by rgbkrk** [ImmoweltGroup/flow-mono-cli#23]
Sadly we're not able to be on yarn workspaces yet due to an electron builder issue, yet I'd still love to use this project in our monorepo that does use flow. Is it possible?

**Comment by Inkdpixels** [comment]
Hey @rgbkrk! It should definitely be possible to use it without using yarn itself, the only thing we require in your project is the yarn workspace configuration, which is just a bare property in your root `package.json`, so just add it and let me know how it works or if you have any problems! :)

**Comment by Inkdpixels** [comment]
@rgbkrk If you have any problems setting it up with plain lerna, please let us know ! :)
