### ISSUE TITLE
Need a new release to address a new npm security vulnerability

### ISSUE THREAD

**Issue by kaiyoma** [ImmoweltGroup/flow-mono-cli#260]
Version 1.5.0 pulls in version 4.6.1 of `lodash.merge`, which has a security vulnerability that appears in `yarn audit`:

https://github.com/ImmoweltGroup/flow-mono-cli/blob/v1.5.0/package.json#L52
https://www.npmjs.com/advisories/1066

This package dependency has already been fixed in master (by bumping the version to 4.6.2), but there's been no releases in the last 4 months. Can we get a new point release to address this?

**Comment by lpww** [comment]
Yes please!

**Comment by sirgalleto** [comment]
+1

**Comment by Romischart** [comment]
We are now updated dependencies, also fixed changed behaviour after v1.5.0

**Comment by lpww** [comment]
Great, thanks!
