### ISSUE TITLE
Cannot resolve module in the root node_modules

### ISSUE THREAD

**Issue by HsuTing** [ImmoweltGroup/flow-mono-cli#310]
I use `flow-mono-cli` in my monorepo. This worked very well before I installed `graphql` in my package. I got the error:

```sh
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ ../../node_modules/graphql/execution/execute.js.flow:3:39

Cannot resolve module iterall.

     1│ // @flow strict
     2│  
     3│ import { forEach, isCollection } from 'iterall';
     4│  
     5│ import inspect from '../jsutils/inspect';
     6│ import memoize3 from '../jsutils/memoize3';
```

`iterall` is the `dependencies` of the `graphql`. I did not include this package in the root `package.json`. Is any solution to fix this problem? 
[Here](https://github.com/HsuTing/test-flow) is my reproduced repo.

**Comment by Romischart** [comment]
Thank you for your response!
Oh ok, iterall is a dependency of graphql... and deep linking is not included in flow-mono-cli.

did you try to use `[declarations]` section in `.flowconfig`
```
[declarations]
.*/node_modules/graphql/.*
```

I have tested it on you example project and it worked for me 👌

**Comment by HsuTing** [comment]
This work!!
Thank you @Romischart 😸
