### ISSUE TITLE
Nested deps in React Native

### ISSUE THREAD

**Issue by Ashoat** [ImmoweltGroup/flow-mono-cli#60]
First of all thanks for creating this library! Excited to try Yarn Workspaces but need to get it working with my Flow config first.

I've whittled it down to a single error in my React Native package:
```js
Error: ../node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:32
 32: const warning = require('fbjs/lib/warning');
                             ^^^^^^^^^^^^^^^^^^ fbjs/lib/warning. Required module not found


Found 1 error
```

`fbjs` is a dependency listed on `react-native`'s `package.json`. `react-native` is listed in my React Native package's `package.json`. yarn is able to resolve the dependency and sticks it in the monorepo root `node_modules`. But it seems that because this dependency is nested, `flow-mono create-symlinks` doesn't detect it, and no symlink is created within my React Native package's `node_modules`.

Any advice?

**Comment by Ashoat** [comment]
(I ended up silencing the error by creating a flow-typed stub for fbjs)

**Comment by Inkdpixels** [comment]
@Ashoat excellent, that is exactly what I would've suggested. FYI there is also 

https://immoweltgroup.gitbooks.io/flow-mono-cli/docs/cli/create-stubs.html

which was made for this purpose and might come in handy again! :) If you have other questions, feel free to up another issue! :)

**Comment by Ashoat** [comment]
Thanks for the explanation! I just gave `flow-mono create-stubs` a go, but it created dozens of stubs I don't need, so I decided to opt for the simple manual approach.
