### ISSUE TITLE
yarn lifecycle hooks to rerun create-symlinks

### ISSUE THREAD

**Issue by Ashoat** [ImmoweltGroup/flow-mono-cli#61]
I want to run `create-symlinks` after every install, so I created `postinstall` script that runs in the root package and looks like this:

```
flow-mono create-symlinks lib/.flowconfig && flow-mono create-symlinks web/.flowconfig && flow-mono create-symlinks native/.flowconfig && flow-mono create-symlinks jserver/.flowconfig
```

Unfortunately that hook wasn't being run on every `yarn add` to a sub-package, which only ends up calling the `postinstall` script of that corresponding sub-package. So I tried setting up the following as each sub-package's postinstall script:

```
cd ../; flow-mono create-symlinks lib/.flowconfig
```

But `flow-mono` fails with the error:

```
flow-mono-create-symlinks(1) does not exist, try --help
```

Any advice on how to get this working?

**Comment by Inkdpixels** [comment]
@Ashoat Can you try executing flow-mono with npx, e.g. `cd ../; npx flow-mono create-symlinks lib/.flowconfig`

**Comment by Ashoat** [comment]
Thanks so much, that worked!

**Comment by IanVS** [comment]
@Ashoat I know you posted this a long time ago, but can you explain why you are running `flow-mono create-symlinks` so many times?  Shouldn't it only be necessary to run it once, where the argument is a "fallback" flow config that's only used if one of your workspaces doesn't have its own?  I'm still trying to figure out how to set all this up.

**Comment by Ashoat** [comment]
Many tools expect to find all of your node modules within the local `node_modules` folder. Tooling is gradually being updated to support monorepo structures like yarn workspaces, but until then stuff might not work. Flow is one example of tooling that has yet to build in support for `yarn workspaces` (to my knowledge). I use `flow-mono create-symlinks` to make sure the local `node_modules` folder has a "folder" for each node module, even if it's been "hoisted" to the root `node_modules` due to being shared with another project in the monorepo.

The reason I run `create-symlinks` after each install is to make sure all the symlinks are there for any new node module I may have added.
