### ISSUE TITLE
Yarn workspaces using nohoist fails: workspaces.map is not a function 

### ISSUE THREAD

**Issue by AndrewJack** [ImmoweltGroup/flow-mono-cli#91]
Running `flow-mono create-symlinks .build/.flowconfig` fails with this exception:
```
✖FATAL::flow-mono-cli: workspaces.map is not a function 
     at fn.catch.e (/Users/user/dev/project/node_modules/flow-mono-cli/dist/lib/async.js:12:42)
``` 

Nohoist - https://yarnpkg.com/blog/2018/02/15/nohoist/

The `package.json` workspaces for nohoist repos are:
```json
{
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/react-native",
      "**/react-native/**"
    ]
  }
}
```

The script in paths.js expects an array, which breaks when using nohoist.
https://github.com/ImmoweltGroup/flow-mono-cli/blob/3d084b8df3de2fee6da80376a3f351e81aceaee5/src/lib/paths.js#L35-L41

I'll have a go at fixing it tomorrow if it hasn't been fixed by then.

**Comment by Inkdpixels** [comment]
@AndrewJack Awesome spot! A PR to fix this issue would be super welcome! :) 💯
