### ISSUE TITLE
install-types hangs at updating the global flow-typed definitions cache

### ISSUE THREAD

**Issue by amosyuen** [ImmoweltGroup/flow-mono-cli#96]
When I run `flow-mono-cli install-types`, it hangs at updating the global flow-typed definitions cache. I've left it running for more than 10 minutes.

If I run `flow-typed update-cache` it completes in about 6s.

Running on windows. Node v8.9.4

**Comment by amosyuen** [comment]
Looks like the problem is that I didn't have a `.flowmonorc` or config, and so it failed to find the config and hangs forever. Probably should print an error message instead.

**Comment by Inkdpixels** [comment]
@amosyuen Thats quite a nice catch! Thanks for creating this issue, would you like to give this a try and add the error message case?

**Comment by tibdex** [comment]
I stumbled on this issue too on Windows. On Linux it seems to be working fine.
 
Maybe you could use [cosmiconfig](https://www.npmjs.com/package/cosmiconfig) instead of rolling your own https://github.com/ImmoweltGroup/find-config-up. It's what [Prettier](https://prettier.io/docs/en/configuration.html) does for instance. :wink:

**Comment by Inkdpixels** [comment]
@tibdex oh wow, haven't known this package. This is definitely a must, as well as deprecating our own package. Thanks a lot! :)

**Comment by Inkdpixels** [comment]
Fix is in master, release should be out in a second. If you experience that this commit has not fixed this issue, feel free to comment on this issue again or even create a new one. 

Again, thanks a lot @tibdex 💯

**Comment by tibdex** [comment]
Wow, that was fast :zap:, thanks a lot @Inkdpixels!

However, for my use-case, I don't need to configure `flow-mono-cli` at all as it works out of the box. Thus, I would like to not have to specify any config at all.

Based on [cosmiconfig's source](https://github.com/davidtheclark/cosmiconfig/blob/a3e135bbeeadf89c0b47a07b6c77ceaa70843fbe/flow-typed/defs.js#L1-L5), in:

https://github.com/ImmoweltGroup/flow-mono-cli/blob/2a0555eec082f8092379f9a0c96cdf0b26be0729/src/lib/config.js#L34-L36

`results` can be `null` so `return merge({}, defaults, results.config)` throws `Cannot read property 'config' of null`.

Can you please change this line to: 

```javascript
return results ? merge({}, defaults, results.config) : defaults;
```

or something equivalent? This way the config would really be optional.

Thanks a lot again for this package, it's really handy!

**Comment by Inkdpixels** [comment]
@tibdex thats so correct! The implementation was quite a quick shot since I just wanted to get it done tbh, will push another fix now 👍
