### ISSUE TITLE
Hangs on node:9-apline 

### ISSUE THREAD

**Issue by FezVrasta** [ImmoweltGroup/flow-mono-cli#97]
If you run `flow-mono create-symlinks .flowconfig` on a Docker image with `node:9-alpine` it will hang forever.

Locally on macOS it works just fine, same Node version.

**Comment by FezVrasta** [comment]
The problem seems related to `find-config-up`, it hangs when it gets executed.

**Comment by Inkdpixels** [comment]
@FezVrasta Thanks for reporting this issue! Will create an issue in the corresponding repo of `find-config-up` and investigate it further! 👍

**Comment by Inkdpixels** [comment]
Should also be solved since we moved from `find-config-up` to `cusomiconfig` recently. If you experience the same issue with the latest version please inform us in this or a separate issue, thanks a lot again @FezVrasta for reporting it in the first place! 💯 👍
